import 'App.css'
import { useEffect, useState } from 'react'
import { styled } from 'styled-components'
import { BoundedCenteringContainer, COLOR } from 'Utils'
import { HeaderWithContentControls } from 'HeaderWithContentPositionControls'
import { MainContentWithArticle } from 'MainContent'
import CONTENT_REPO from 'data.json'

const MAX_CONTENT_POSITION = CONTENT_REPO.length

const FooterCitationList = styled.ul`
  padding-top: 0;

  & > *:not(:last-child) {
    margin-bottom: 0.5rem;
  }
`

const Citation = styled.li`
  font-style: italic;
  color: ${COLOR.primary600};
`

const App = () => {
  useEffect(() => {
    document.title = 'Universal Design'
  }, [])

  const [contentIndex, setContentIndex] = useState({
    position: 0,
    verbosity: 'full',
    voice: 'suzanne',
  })

  const contentData = CONTENT_REPO[contentIndex.position]

  return (
    <BoundedCenteringContainer>
      <HeaderWithContentControls
        contentPosition={contentIndex.position}
        maxContentPosition={MAX_CONTENT_POSITION}
        setContentIndex={setContentIndex}
      />
      <MainContentWithArticle
        contentIndex={contentIndex}
        contentData={contentData}
        setContentIndex={setContentIndex}
      />
      <footer aria-label="citations">
        <FooterCitationList>
          <Citation style={{ 'margin-bottom': '.5rem' }}>
            Text and icons generated by ChatGPT.
          </Citation>
          <Citation>
            Edited by Adrian Rodriguez and Suzanne Ender
          </Citation>
          <Citation>
            Style and code by Adrian Rodriguez
          </Citation>
        </FooterCitationList>
      </footer>
    </BoundedCenteringContainer>
  )
}

export default App
